# Generated by Django 2.1.3 on 2018-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=255, null=True)),
                ('testPate', models.CharField(max_length=255, null=True)),
                ('testMate', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
