# Generated by Django 2.1.3 on 2018-11-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='testModel',
        ),
    ]
